//find your waybar config part that has your list of displays in waybar
//should look like this
// Modules Right    
//"modules-right": ["custom/mullvad",]

//Below is an example of mine but don't copy and paste this or it will have issues

// Modules Right    
    "modules-right": [
        "custom/updates",
        "pulseaudio",
        "network",
	    "custom/mullvad",
        "tray",
        "clock"
    ]
